### PR TITLE
Install FunScript core libs using Paket

### PR DESCRIPTION
**Pull request by mcgee**
What do you think about installing FunScript using Nuget? AFAIK, only atom bindings can not be installed this way, isn't it?

### CODE REVIEW

**Comment by tpetricek** [comment]
When I did some work on this (some time ago), I did some crazy hack that inlined the dependencies of the `atom` binding (because FunScript wouldn't handle loops in the dependencies), so things like `space_pen` were actually inlined in `atom`. But maybe that is no longer needed??

**Comment by forki** [comment]
This project uses paket instead of nuget.exe see http://fsprojects.github.io/Paket/

To do the same thing add the projects to paket.dependencies in the root and manipulate the paket.references in the project folder. Then run paket install.

**Comment by forki** [comment]
I did something similar for paket.atom se https://github.com/fsprojects/Paket.Atom/pull/11

**Comment by Krzysztof-Cieslak** [comment]
I've discussed with Steffen similar idea here - https://github.com/ZachBray/FunScript/issues/177.

FunScrip bindings DLLs are generated from our custom TypeScript definition files which are intended to be changed in some cases ( changes of API etc.). For example all those custom bindings https://github.com/fsprojects/FSharp.Atom/blob/develop/src/Bindings.fs#L37-L123 should be moved to TypeScript files at some point in the future and bindings should be regenerated. Even if some other bindings files can be found on Nuget we need our custom versions.

Those bindings can be regenerated in build process, Tomas has written FAKE task to do so. 

So for bindings file I would leave things as it is right now. 

Getting FunScript core package should work well, I don't think we did any changes in it. But as it was said - we use Paket not NuGet directly.

**Comment by mcgee** [comment]
Okay, I have installed FunScript core package using Paket. 
To remove remaining libs in ``lib`` folder from repository and generate them when necessary seems to be good idea, but I think it's out of scope of this pull request

**Comment by mcgee** [comment]
However, Paket tool completely regenerated .fsproj file, so it seems to be some conflicts there, I'm sorry

**Pull request merged**
